// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWHHswoLXRDclBwW-AHh-Fx4GqjdqyPtg',
    appId: '1:190567880564:web:08295a08c4a99c0edb7e21',
    messagingSenderId: '190567880564',
    projectId: 'shrines-and-temples-app',
    authDomain: 'shrines-and-temples-app.firebaseapp.com',
    storageBucket: 'shrines-and-temples-app.firebasestorage.app',
    measurementId: 'G-X4V7MV0KQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7gLjQkMU0uHt6255zaqsO0mkSUxWJn4',
    appId: '1:190567880564:android:a2c95b8f1f08a52fdb7e21',
    messagingSenderId: '190567880564',
    projectId: 'shrines-and-temples-app',
    storageBucket: 'shrines-and-temples-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApFntkwvUEB7i0HYjbYst9Up15ckJFYUs',
    appId: '1:190567880564:ios:12bce0199e97078edb7e21',
    messagingSenderId: '190567880564',
    projectId: 'shrines-and-temples-app',
    storageBucket: 'shrines-and-temples-app.firebasestorage.app',
    iosBundleId: 'com.example.geoguessurTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApFntkwvUEB7i0HYjbYst9Up15ckJFYUs',
    appId: '1:190567880564:ios:12bce0199e97078edb7e21',
    messagingSenderId: '190567880564',
    projectId: 'shrines-and-temples-app',
    storageBucket: 'shrines-and-temples-app.firebasestorage.app',
    iosBundleId: 'com.example.geoguessurTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWHHswoLXRDclBwW-AHh-Fx4GqjdqyPtg',
    appId: '1:190567880564:web:1841458082cd9599db7e21',
    messagingSenderId: '190567880564',
    projectId: 'shrines-and-temples-app',
    authDomain: 'shrines-and-temples-app.firebaseapp.com',
    storageBucket: 'shrines-and-temples-app.firebasestorage.app',
    measurementId: 'G-GEQLPNXB3T',
  );
}
